collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.5422804
color:
  saturation: 0.4989259
  brandStrength: 0.8219622
  lightness: 0.6396348
  brandColors:
    - '#C0C9C8'
    - '#112A41'
    - '#3E668C'
    - '#6E8AA5'
    - '#DFFE6C'
  rhythmicContrast: 0.6611171
layout_spectrum: 1
name: curtOphoto
