layout_spectrum: 1
color:
  saturation: 0.3243352
  lightness: 0.8278242
  brandStrength: 0.8219622
  rhythmicContrast: 0.1979967
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
typography_spectrum: 0.5422804
name: curtOphoto
